---
apiVersion: v1
kind: Pod
metadata:
   name: vprodb
   labels:
     app: vprodb

spec:
   containers:
    - name: vprodbcontainer
      image: santanubose03/vprodb:2.0
      ports:
        - name: vprodb-port
          containerPort: 3306
      volumeMounts:
         - mountPath: /var/lib/mysql
           name: vprodb-data
           readOnly: false
      env:
       - name: MYSQL_DATABASE
         valueFrom: 
           secretKeyRef:
              name: db-secret
              key: MYSQL_DATABASE
                
       - name: MYSQL_ROOT_PASSWORD
         valueFrom: 
           secretKeyRef:
              name: db-secret
              key: MYSQL_ROOT_PASSWORD
   volumes:
    - name: vprodb-data
    # mount /data/foo, but only if that directory already exists
      hostPath:
        path: /data # directory location on host
        type: DirectoryOrCreate  # this field is optional      
    #  configMap:
    #    name: db-config
    #    items:
    #    - key: "game.properties"
    #      path: "game.properties"
        
    #    - key: "user-interface.properties"
    #      path: "user-interface.properties"    
...

