---
apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  selector:
    app: vproapp  # Must match the pod's label
  ports:
    - protocol: TCP
      port: 8080       # External port (clients use this)
      targetPort: 8080  # The port your app is listening on inside the container
        
  type: ClusterIP  # Exposes the service externally

...    
