---
apiVersion: v1
kind: Pod
metadata:
   name: vprocache01
   labels:
     app: vprocache01

spec:
   containers:
    - name: vprocachecontainer
      image: memcached:1.6
      ports:
        - name: vprocache-port
          containerPort: 11211

...
