---
apiVersion: v1
kind: Service
metadata:
  name: vprocache-service
spec:
  selector:
    app: vprocache01  # Must match the pod's label
  ports:
    - protocol: TCP
      port: 11211      # Internal  port (clients use this)
      targetPort: 11211  # The port your app is listening on inside the container

  type: ClusterIP  # Exposes the service externally

...
