---
apiVersion: v1
kind: Service
metadata:
  name: vprodb-service
spec:
  selector:
    app: vprodb  # Must match the pod's label
  ports:
    - protocol: TCP
      port: 3306        # External port (clients use this)
      targetPort: 3306  # The port your app is listening on inside the container
     
  type: ClusterIP # ✅ Only accessible inside the cluster

...
