---
apiVersion: v1
kind: Service
metadata:
  name: vprormq-service
spec:
  selector:
    app: vprormq01  # Must match the pod's label
  ports:
    - protocol: TCP
      port: 5672       # Internal  port (clients use this)
      targetPort: 5672  # The port your app is listening on inside the container

  type: ClusterIP # the service externally

...
