pipeline:
  identifier: Build_santanubose03_vprofile_project_hkhcoder_1753467800422
  name: Build vprofile-project-hkhcoder
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1753467734625
        repoName: santanubose03/vprofile-project-hkhcoder
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: mvn
                  name: mvn build
                  spec:
                    command: mvn clean install
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Docker
        type: CI
