pipeline:
  identifier: Build_santanubose03_vprofile_project_hkhcoder_1753467800422
  name: Build vprofile-project-hkhcoder
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1753467734625
        repoName: santanubose03/vprofile-project-hkhcoder
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: mvn
                  name: mvn build
                  spec:
                    command: mvn clean install -DskipTests
                  timeout: ""
                  type: Run
               
              - step:
                  identifier: upload_artifact
                  name: Upload WAR Artifact
                  type: Run
                  spec:
                    command: |
                      mkdir -p /harness/artifacts
                      cp target/*.war /harness/artifacts/
                      cd /harness/artifacts
                      ls -ltr
                  
          platform:
            arch: Amd64
            os: Linux
          runtime:
            type: Docker
            spec:
              image: maven:3.8.6-openjdk-17
        type: CI
